# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

default_install_hook_types:
  - commit-msg
  - post-commit
  - pre-commit

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
  - repo: "https://github.com/asottile/setup-cfg-fmt"
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - "--min-py3-version=3.8"
  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--py38-plus"
          - "--application-directories=.:src"
  - repo: "https://github.com/asottile/pyupgrade"
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"
  - repo: "https://github.com/psf/black"
    rev: 23.10.1
    hooks:
      - id: black
        args:
          - "--target-version=py38"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.6.1
    hooks:
      - id: mypy
        args:
          - "--python-version=3.8"
        additional_dependencies:
          - gitpython~=3.1.37
          - pep440~=0.1.2
          - pydantic~=2.4.0
          - pytest
          - questionary~=2.0.1
          - semver~=3.0.1
          - types-pyyaml
          - types-setuptools
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: "https://github.com/PyCQA/pylint"
    rev: v3.0.1
    hooks:
      - id: pylint
        additional_dependencies:
          - gitpython~=3.1.37
          - pep440~=0.1.2
          - pydantic~=2.4.0
          - pytest
          - pyyaml~=6.0.1
          - questionary~=2.0.1
          - semver~=3.0.1
  - repo: "https://github.com/PyCQA/bandit"
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - ".[toml]"
  - repo: "https://github.com/PyCQA/pydocstyle"
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - "--convention=numpy"
          - "--explain"
          - "--source"
        additional_dependencies:
          - ".[toml]"
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: 3.12.0
    hooks:
      - id: commitizen
        stages: [post-commit]
