# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

default_install_hook_types:
  - commit-msg
  - post-commit
  - pre-commit

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
  - repo: "https://github.com/asottile/setup-cfg-fmt"
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - "--min-py-version=3.8"
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v0.1.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ --fix ]
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.7.1
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - gitpython~=3.1.37
          - pep440~=0.1.2
          - pydantic~=2.4.0
          - pytest
          - questionary~=2.0.1
          - semver~=3.0.1
          - types-pyyaml
          - types-setuptools
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [post-commit]
