# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
  autoupdate_commit_msg: "ci(pre-commit): autoupdate"

default_install_hook_types:
  - commit-msg
  - post-commit
  - pre-commit

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: name-tests-test
  - repo: "https://github.com/asottile/setup-cfg-fmt"
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - "--min-py3-version=3.8"
  - repo: "https://github.com/asottile/reorder_python_imports"
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--py38-plus"
  - repo: "https://github.com/asottile/pyupgrade"
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"
  - repo: "https://github.com/psf/black"
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - "--target-version=py38"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.1.1
    hooks:
      - id: mypy
        args:
          - "--python-version=3.8"
          - "--disallow-untyped-defs"
          - "--disallow-incomplete-defs"
        additional_dependencies:
          - gitpython~=3.1.30
          - pep440~=0.1.2
          - pytest
          - questionary~=1.10.0
          - semver~=2.13.0
          - types-pyyaml
          - types-setuptools
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: "https://github.com/PyCQA/pylint"
    rev: v2.17.0
    hooks:
      - id: pylint
        additional_dependencies:
          - gitpython~=3.1.30
          - pep440~=0.1.2
          - pytest
          - pyyaml~=6.0
          - questionary~=1.10.0
          - schema~=0.7.5
          - semver~=2.13.0
  - repo: "https://github.com/PyCQA/bandit"
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - ".[toml]"
  - repo: "https://github.com/PyCQA/pydocstyle"
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - "--convention=numpy"
          - "--explain"
          - "--source"
        additional_dependencies:
          - ".[toml]"
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [post-commit]
