name: Build python package and publish to TestPyPI and PyPI

on:
  push:
    branches: [ main ]
    tags: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip3 install build

    - name: Build package
      run: python3 -m build --sdist --wheel --outdir dist .

    - name: Publish package to TestPyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags') && !contains(github.ref, 'dev')
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
