name: Run pytest and publish coverage to Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest-and-coverage:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v3.6.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install .
        pip3 install -r tests/requirements.txt

    - name: Run pytest
      run: pytest --cov=project_release --cov-report=term --cov-report=xml tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
      with:
        files: coverage.xml
        fail_ci_if_error: true
